apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-quality-api
  labels:
    app: face-quality
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: face-quality
  template:
    metadata:
      labels:
        app: face-quality
    spec:
      containers:
      - name: face-quality-container
        image: ${ACR_LOGIN_SERVER}/face-detection-quality:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: face-api-secrets
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10